## Pre-declare environmental variables
environment-template-common: &environment-template-common
  DEBIAN_FRONTEND: "noninteractive"
  DEBIAN_PRIORITY: "critical"
  DEBCONF_NOWARNINGS: "yes"
  DEBFULLNAME: "GobySoft CircleCI"
  DEBEMAIL: "toby@gobysoft.org"
  QUILT_PATCHES: debian/patches
  QUILT_REFRESH_ARGS: "-p ab --no-timestamps --no-index --strip-trailing-whitespace"
  SOURCE_WORKING_DIRECTORY: "/root/package-src"

environment-template-amd64: &environment-template-amd64
  TARGET_ARCH: "amd64"
  DEB_BUILD_OPTIONS: "parallel=4"
  # one job only must do the source build for each distro
  DO_SOURCE_BUILD: "true"

environment-template-arm64: &environment-template-arm64
  TARGET_ARCH: "arm64"
  DEB_BUILD_OPTIONS: "parallel=4 nocheck"
  
environment-template-focal: &environment-template-focal
  DISTRO_RELEASE_CODENAME: "focal"
  DISTRO_RELEASE_VERSION: "ubuntu20.04"

  
## Pre-declare Docker containers
docker-base-focal: &docker-base-focal
  - image: gobysoft/ubuntu-build-base:20.04.1
    
## Pre-declare job templates
job-template-amd64: &job-template-amd64
  working_directory: /root/debian
  steps:
    - checkout
    - run: &run-update-apt
        name: Update apt packages
        command: apt-get update && apt-get dist-upgrade -y
    - run: &run-import-gpg
        name: Import GPG key
        command: echo -e "$GPG_KEY" | gpg --import
    - attach-workspace: &attach-src-workspace
        at: /root/src
    - run: &run-extract-src
        name: Extract the original source tarball
        command: |
          cp /root/src/*.orig.tar.gz ${CIRCLE_WORKING_DIRECTORY}/.. &&
          mkdir -p ${SOURCE_WORKING_DIRECTORY} && cd ${SOURCE_WORKING_DIRECTORY} &&
          tar xfz ../*.orig.tar.gz --strip-components=1
    - run: &run-nest-deb
        name: Nest debian source into project source and do changelog substitution
        command: |
          cp -r /root/debian ${SOURCE_WORKING_DIRECTORY} &&
          cp /root/src/changelog ${SOURCE_WORKING_DIRECTORY}/debian &&
          sed -i "s/DISTRORELEASEVERSION/${DISTRO_RELEASE_VERSION}/;s/DISTRORELEASECODENAME/${DISTRO_RELEASE_CODENAME}/" ${SOURCE_WORKING_DIRECTORY}/debian/changelog
    - run: &run-install-build-deps
        name: Install build dependencies
        command: |
          cd ${SOURCE_WORKING_DIRECTORY} &&
          mk-build-deps -a ${TARGET_ARCH} --host-arch ${TARGET_ARCH} --build-arch amd64 -t "apt-get -y --no-install-recommends -o Debug::pkgProblemResolver=yes" -i "debian/control" &&
          rm -f ${SOURCE_WORKING_DIRECTORY}/*-build-deps*.*
    - run: &run-build-pkg
        name: Build the Debian package 
        command: |
          cd ${SOURCE_WORKING_DIRECTORY} &&
          export DPKG_BUILDPACKAGE_BUILD_TYPE="-B"
          # default is to do source and binary build
          [[ "${DO_SOURCE_BUILD}" == "true" ]] && DPKG_BUILDPACKAGE_BUILD_TYPE=""        
          CONFIG_SITE=/etc/dpkg-cross/cross-config.${TARGET_ARCH} && dpkg-buildpackage -k954A004CD5D8CF32 -a${TARGET_ARCH} ${DPKG_BUILDPACKAGE_BUILD_TYPE}
    - run: &run-store-next-build
        name: Store deb files for next build
        command: |
          cd ${SOURCE_WORKING_DIRECTORY} &&
          mkdir -p /root/deb &&
          find .. -maxdepth 1 -type f -exec cp {}  /root/deb \; &&
          rm -f /root/deb/*-build-deps*.deb
    - run: &run-store-for-artifacts
        name: Store deb files for storing artifacts
        command: mkdir -p /tmp/deb && cp /root/deb/* /tmp/deb
    - store_artifacts: &store
        path: /tmp/deb
    - run: &remove-orig-source
        name: Remove original source file to avoid conflicts in merging
        command: |        
          rm -f /root/deb/*.orig.tar.gz || true
    - persist_to_workspace: &persist-debs
        root: /root/deb
        paths:
          - '*.dsc'
          - '*.tar.xz'
          - '*.deb'
          - '*.ddeb'
          - '*.changes'
          - '*.buildinfo'
  
job-template-cross: &job-template-cross
  <<: *job-template-amd64

# base upload off Bionic build
job-template-upload: &job-template-upload
  <<: *job-template-amd64
  docker: *docker-base-focal
  
## Begin actual config
version: 2
workflows:
  version: 2
  commit:
    jobs:
      - get-orig-source
            
      - amd64-focal-build:
          requires:
            - get-orig-source
      - arm64-focal-build:
          requires:
            - get-orig-source
            
      - upload:
          requires:
            - arm64-focal-build
            - amd64-focal-build
            
jobs:
  get-orig-source:
    <<: *job-template-amd64
    docker: *docker-base-focal
    environment:
      <<: *environment-template-common
      <<: *environment-template-focal
      <<: *environment-template-amd64
    steps:
      - checkout
      - run:
          name: Install required packages
          command: |          
            apt-get update && apt-get -y install cdbs wget     
      - run:
          name: Get original source tarball
          command: |
            wget http://archive.ubuntu.com/ubuntu/pool/universe/h/h5py/h5py_3.6.0.orig.tar.gz  &&
            mkdir -p /root/src &&
            mv *.tar.gz /root/src
      - run:
          name: Add changelog entry 
          command: |
            cd .. &&
            export NEWVERSION="$(echo /root/src/*.orig.tar.gz | sed 's/.*_\(.*\)\.orig\.tar\.gz/\1/')"
            COMMENT="Autobuild for version ${NEWVERSION}" &&
            dch --newversion=${NEWVERSION}-3~jaia~DISTRORELEASEVERSION.1 -D DISTRORELEASECODENAME "${COMMENT}" &&
            cp debian/changelog /root/src
      - store_artifacts:
          path: /root/src
      - persist_to_workspace:
          root: /root/src
          paths:
            - '*.tar.gz'
            - 'changelog'
            

  amd64-focal-build:
    <<: *job-template-amd64
    docker: *docker-base-focal
    environment:
      <<: *environment-template-common
      <<: *environment-template-focal
      <<: *environment-template-amd64
  arm64-focal-build: 
    <<: *job-template-cross
    docker: *docker-base-focal
    environment:
      <<: *environment-template-common
      <<: *environment-template-focal
      <<: *environment-template-arm64

      
  upload:
    <<: *job-template-upload
    environment:
      <<: *environment-template-common
      <<: *environment-template-focal
      <<: *environment-template-amd64
    resource_class: small
    steps: &steps-upload
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "5a:bc:88:89:21:a2:a0:cd:68:07:b5:26:f0:64:28:e9"
      - run: *run-import-gpg
      - attach-workspace:
          at: /root/deb
      - attach-workspace: *attach-src-workspace
      - run:
          name: Move original source into output directory
          command: mv /root/src/* /root/deb
      - run:      
          name: Upload packages to packages.jaia.tech
          command: |
            echo 'trusted-key 954A004CD5D8CF32' >> ~/.gnupg/gpg.conf
            echo '|1|OX0vdRrGPWjPOTrl5R/joY37TX0=|teBg0IDnMu36QiR2UL4usur+XyY= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBIz46MTlT0H1Z9P4Msh32nhdbQ9D/CEfnIavB+pRtHZZ3oKrS6ZWKxTOUHTKgw+KKUMSKzdW7XtPaBKb0Qndahw=' >> ~/.ssh/known_hosts
            for change_file in /root/deb/*.changes;
            do dput -c ${CIRCLE_WORKING_DIRECTORY}/.circleci/dput.cf jaiabot-release-1.y $change_file;
            do dput -c ${CIRCLE_WORKING_DIRECTORY}/.circleci/dput.cf jaiabot-beta-1.y $change_file;
            do dput -c ${CIRCLE_WORKING_DIRECTORY}/.circleci/dput.cf jaiabot-continuous-1.y $change_file;
            done
